// Generated by CoffeeScript 1.9.3
(function() {
  var error, net, rethinkdb;

  net = require('./net');

  rethinkdb = require('./ast');

  error = require('./errors');

  rethinkdb.connect = net.connect;

  rethinkdb.Error = error;

  module.exports = rethinkdb;

}).call(this);
